version: '3.1'

services:
    phpmyadmin:
        image: phpmyadmin
        restart: always
        ports:
            - 8090:80
        environment:
            - PMA_ARBITRARY=1
            - PMA_PORT=3306
        